### ISSUE TITLE
Coursework feedback

### ISSUE THREAD

**Issue by NYBACHOK** [Rewriter00x/my_parser_kma_group_3_DB#1]
Student: напиши своє ім'я

Для прохідного:
✔️ ! CLI: Create a command-line interface that includes commands to parse a file and to display help and credits information. Тобто тобі потрібно зробити ще щось по типу --credits де буде інформація про автора, якась версія і все в принципі.
✔️ ! Brief Description:
✔️ ! Project Name:
✔️ ! Grammar Rules:
✔️ ! Unit Tests:
✔️ ! Core Files:

Для мааксимального:
❌ File System: ще і запис у файл, який визначає користувач
✔️ Test Coverage:
❌ Error Handling: anyhow лише для тестів, а thiseror для lib i main
✔️ cargo fmt:
❌ cargo clippy: коли переробиш 
❌ makefile: A makefile should include commands to launch the program and to run tests, format and clipply before committing as well other useful commands. 
❌ Completeness:
✔️ Including a diagram or grammar in the Readme.md:
❌ Documentation: документація методів у lib 
❌ Publishing:  коли переробиш 

Курсова може бути зарахована ✔️
Бал: 11/25

**Comment by Rewriter00x** [comment]
Updated cli. Does it meet requirements now? If so, please put me a mark

**Comment by NYBACHOK** [comment]
Так. Більше з нею ніяких проблем
